sudo apt-get install libsdl1.2-dev
sudo apt-get install libsdl-ttf2.0-dev
sudo apt-get install libsdl-image1.2-dev
sudo apt-get install swig
sudo apt-get install libboost1.40-dev
sudo apt-get install g++
sudo apt-get install python2.6-dev
sudo cp assimp/lib/libassimp.so /usr/lib/libassimp.so
sudo cp assimp/lib/libassimp.so.1 /usr/lib/libassimp.so.1