dofile("Tags.lua")
hMap=      walls.bws..walls.bws..walls.bws..walls.bws..walls.bws..walls.bws..walls.bws..";"
hMap=hMap..walls.lws..walls.e  ..walls.e  ..walls.e  ..walls.e  ..walls.e  ..walls.rws..";"
hMap=hMap..walls.lws..walls.e  ..walls.e  ..walls.e  ..walls.e  ..walls.e  ..walls.rws..";"
hMap=hMap..walls.lws..walls.e  ..walls.e  ..walls.e  ..walls.e  ..walls.e  ..walls.rws..";"
hMap=hMap..walls.lws..walls.e  ..walls.e  ..walls.e  ..walls.e  ..walls.e  ..walls.rws..";"
hMap=hMap..walls.fws..walls.win..walls.fws..walls.dor..walls.fws..walls.win..walls.fws..";"

fMap=      til.ti1..til.ti2..til.ti1..til.cpt..til.cpt..til.cpt..til.cpt..";"
fMap=fMap..til.ti1..til.ti2..til.ti1..til.cpt..til.cpt..til.cpt..til.cpt..";"
fMap=fMap..til.ti1..til.ti2..til.ti1..til.cpt..til.cpt..til.cpt..til.cpt..";"
fMap=fMap..til.wod..til.wod..til.wod..til.cpt..til.cpt..til.cpt..til.cpt..";"
fMap=fMap..til.wod..til.wod..til.wod..til.cpt..til.cpt..til.cpt..til.cpt..";"
fMap=fMap..til.wod..til.wod..til.wod..til.cpt..til.cpt..til.cpt..til.cpt..";"
  
cMap=      til.roe..til.roe..til.roe..til.roe..til.roe..til.roe..til.roe..";"
cMap=cMap..til.rof..til.rof..til.rof..til.rof..til.rof..til.rof..til.rof..";"
cMap=cMap..til.rof..til.rof..til.rof..til.rof..til.rof..til.rof..til.rof..";"
cMap=cMap..til.rof..til.rof..til.rof..til.rof..til.rof..til.rof..til.rof..";"
cMap=cMap..til.rof..til.rof..til.rof..til.rof..til.rof..til.rof..til.rof..";"
cMap=cMap..til.ros..til.ros..til.ros..til.ros..til.ros..til.ros..til.ros..";"  