dofile("Buildings/Tags.lua")
hMap=      w.bws..w.bws..w.bws..w.bws..w.bws..w.bws..w.bws..";"
hMap=hMap..w.lws..w.e  ..w.e  ..w.e  ..w.e  ..w.e  ..w.rws..";"
hMap=hMap..w.lws..w.e  ..w.e  ..w.e  ..w.e  ..w.e  ..w.rws..";"
hMap=hMap..w.lws..w.e  ..w.e  ..w.e  ..w.e  ..w.e  ..w.rws..";"
hMap=hMap..w.lws..w.e  ..w.e  ..w.e  ..w.e  ..w.e  ..w.rws..";"
hMap=hMap..w.lcs..w.win..w.fws..w.dor..w.fws..w.win..w.rcs..";"

fMap=      t.ti1..t.ti2..t.ti1..t.cpt..t.cpt..t.cpt..t.cpt..";"
fMap=fMap..t.ti1..t.ti2..t.ti1..t.cpt..t.cpt..t.cpt..t.cpt..";"
fMap=fMap..t.ti1..t.ti2..t.ti1..t.cpt..t.cpt..t.cpt..t.cpt..";"
fMap=fMap..t.wod..t.wod..t.wod..t.cpt..t.cpt..t.cpt..t.cpt..";"
fMap=fMap..t.wod..t.wod..t.wod..t.cpt..t.cpt..t.cpt..t.cpt..";"
fMap=fMap..t.wod..t.wod..t.wod..t.cpt..t.cpt..t.cpt..t.cpt..";"
  
cMap=      t.roe..t.roe..t.roe..t.roe..t.roe..t.roe..t.roe..";"
cMap=cMap..t.rof..t.rof..t.rof..t.rof..t.rof..t.rof..t.rof..";"
cMap=cMap..t.rof..t.rof..t.rof..t.rof..t.rof..t.rof..t.rof..";"
cMap=cMap..t.rof..t.rof..t.rof..t.rof..t.rof..t.rof..t.rof..";"
cMap=cMap..t.rof..t.rof..t.rof..t.rof..t.rof..t.rof..t.rof..";"
cMap=cMap..t.ros..t.ros..t.ros..t.ros..t.ros..t.ros..t.ros..";"  